# 服务配置（每个单独的服务都需要配置对应的端口）

serve:
  port: 3000
  prefix: api # 路径前缀

# 数据库配置

db:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: nest_serve_db
  synchronize: true # 自动同步表

# 缓存配置

cache:
  redis: # 有值时，使用 redis 做缓存服务器
    host:
    port:
    auth_pass:

# Swagger 配置

swagger:
  title: PartTime接口文档
  description: code:状态码，message:提示信息，data:返回值
  path: swagger

# 日志存放目录

logsPath: logs